#!/bin/bash

set -e

scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
# function names
setup_neovim()
{
if [[ -d ~/.config/nvim ]]; then
  rm -fr ~/.config/nvim/
fi
if [[ -d ~/.nvim/ ]]; then
    rm -fr ~/.nvim/
fi

mkdir ~/.config/nvim/
mkdir ~/.nvim/undodir -p
cp -r $scriptDir/neovim/autoload/ ~/.config/nvim/
ln -s $scriptDir/neovim/init.vim ~/.config/nvim/init.vim
}

setup_tmux()
{
rm ~/.tmux.conf
ln -s $scriptDir/tmux/.tmux.conf  ~/.tmux.conf
}

setup_vscode()
{
rm ~/.config/Code/User/settings.json ~/.config/Code/User/keybindings.json
mkdir ~/.config/Code/User/
ln -s $scriptDir/vscode/settings.json ~/.config/Code/User/settings.json
ln -s $scriptDir/vscode/keybindings.json ~/.config/Code/User/keybindings.json
}

setup_ideavimrc()
{
rm ~/.ideavimrc
ln -s $scriptDir/ideavimrc/.ideavimrc ~/.ideavimrc
}

setup_all()
{
    setup_neovim
    setup_tmux
    setup_vscode
    setup_ideavimrc
}

list_options()
{
    echo "all"
    echo "neovim"
    echo "tmux"
    echo "vscode"
    echo "ideavimrc"
}

_help()
{
    echo "This script installs dotfiles"
    echo "Usage:"
    echo "init_dotfiles <application>"
    echo ""
    echo "to see all available applications use:"
    echo "init_dotfiles list"
}

# main body


if [ "$1" == "list" ]; then
    list_options
elif [ "$1" == "all" ]; then
     setup_all
elif [ "$1" == "neovim" ]; then
    setup_neovim
elif [ "$1" == "tmux" ]; then
    setup_tmux
elif [ "$1" == "vscode" ]; then
    setup_vscode
elif [ "$1" == "ideavimrc" ]; then
    setup_ideavimrc
else
    _help
fi
