#!/bin/bash
set -e

scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
# function names
setup_neovim()
{
if [[ -d ~/.config/nvim ]]; then
  rm -fr ~/.config/nvim/
fi
if [[ -d ~/.nvim/ ]]; then
    rm -fr ~/.nvim/
fi

mkdir ~/.config/nvim/ -p
mkdir ~/.nvim/undodir -p
cp -r $scriptDir/neovim/autoload/ ~/.config/nvim/
ln -s $scriptDir/neovim/init.vim ~/.config/nvim/init.vim
}

setup_tmux()
{
if [[ -f ~/.tmux.conf ]]; then
	rm ~/.tmux.conf
fi
ln -s $scriptDir/tmux/.tmux.conf  ~/.tmux.conf
}

setup_vscode()
{
rm ~/.config/Code/User/settings.json ~/.config/Code/User/keybindings.json
mkdir ~/.config/Code/User/ 
ln -s $scriptDir/vscode/settings.json ~/.config/Code/User/settings.json
ln -s $scriptDir/vscode/keybindings.json ~/.config/Code/User/keybindings.json
}

setup_aliases()
{
if [[ -f ~/.aliases ]]; then
  rm ~/.aliases
fi
ln -s $scriptDir/aliases/aliases ~/.aliases
if [[ -f ~/.bashrc ]]; then
    echo "" >> ~/.bashrc
    echo "# add my aliases" >> ~/.bashrc
    echo "if [[ -f ~/.aliases ]]; then" >> ~/.bashrc
    echo "    . ~/.aliases" >> ~/.bashrc
    echo "fi"  >> ~/.bashrc
fi

if [[ -f ~/.zshrc ]]; then
    echo "" >> ~/.zshrc
    echo "# add my aliases" >> ~/.zshrc
    echo "source $HOME/.aliases" >> ~/.zshrc
fi
}

setup_npm()
{
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
if [[ -f ~/.profile ]]; then
    echo "" >> ~/.profile
    echo "# add npm prefix" >> ~/.profile
    echo "\"export PATH=~/.npm-global/bin:\$PATH\"" >> ~/.profile
fi
}
setup_ideavimrc()
{
rm ~/.ideavimrc
ln -s $scriptDir/ideavimrc/.ideavimrc ~/.ideavimrc
}

setup_all()
{
    echo "Not available"
}

list_options()
{
    echo "all"
    echo "aliases"
    echo "tmux"
    echo "vscode"
    echo "ideavimrc"
}

_help()
{
    echo "This script installs dotfiles"
    echo "Usage:"
    echo "init_dotfiles <application>"
    echo ""
    echo "to see all available applications use:"
    echo "init_dotfiles list"
}

# main body


for var in "$@"
do
if [ "$var" == "list" ]; then
    list_options
elif [ "$var" == "all" ]; then
     setup_all
elif [ "$var" == "aliases" ]; then
    setup_aliases
elif [ "$var" == "tmux" ]; then
    setup_tmux
elif [ "$var" == "npm" ]; then
    setup_npm
elif [ "$var" == "vscode" ]; then
    setup_vscode
elif [ "$var" == "ideavimrc" ]; then
    setup_ideavimrc
else
    _help
fi
done

# If using i3wm with virtualbox: add this to .xinitrc
# /usr/bin/VBoxClient-all
